# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_gen_init_empty <- function(x) {
    .Call('_generatr_C_gen_init_empty', PACKAGE = 'generatr', x)
}

C_add_element <- function(ptr, elem) {
    invisible(.Call('_generatr_C_add_element', PACKAGE = 'generatr', ptr, elem))
}

C_gen_init_with_vector <- function(x) {
    .Call('_generatr_C_gen_init_with_vector', PACKAGE = 'generatr', x)
}

C_gen_next <- function(ptr, gen_type) {
    .Call('_generatr_C_gen_next', PACKAGE = 'generatr', ptr, gen_type)
}

C_gen_current <- function(ptr, gen_type) {
    .Call('_generatr_C_gen_current', PACKAGE = 'generatr', ptr, gen_type)
}

